@startuml
abstract class OutputStream{

}
OutputStream <|-- FileOutputStream
OutputStream <|-- FilterOutputStream
FilterOutputStream <|-- DataOutputStream
FilterOutputStream <|-- BufferedOutputStream
OutputStream <|-- ByteArrayOutputStream
OutputStream <|-- PipedOutputStream
OutputStream <|-- ObjectOutputStream
@enduml