@startuml
abstract class InputStream{

}
InputStream <|-- FileInputStream
InputStream <|-- FilterInputStream
FilterInputStream <|-- DataInputStream
FilterInputStream <|-- BufferedInputStream
FilterInputStream <|-- PrintStream
InputStream <|-- ByteArrayInputStream
InputStream <|-- StringBufferInputStream
InputStream <|-- PipedInputStream
InputStream <|-- SequenceInputStream
InputStream <|-- ObjectInputStream
@enduml