@startuml
abstract class Reader{
    public int read();
    public int read(char cbuf[]);
}
Reader <|-- InputStreamReader
InputStreamReader <|--FileReader
Reader <|-- BufferedReader
BufferedReader <|-- LineNumberReader
Reader <|-- CharArrayReader
Reader <|-- StringReader
Reader <|-- PipedReader
Reader <|-- FilterReader
FilterReader <|--PushbackReader
@enduml